[project]
name = "benchmark-ensemble-methods-spatial-interpolation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gdal[numpy]>=3.11.4",
    "numpy>=2.3.4",
    "setuptools>=80.9.0",
    "wheel>=0.45.1",
]
