[project]
name = "benchmark-ensemble-methods-spatial-interpolation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gdal>=3.11.4",
]
