[project]
name = "benchmark-ensemble-methods-spatial-interpolation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gdal[numpy]==3.11.4",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "polars>=1.34.0",
    "py7zr>=1.0.0",
    "rasterio>=1.4.3",
    "requests>=2.32.5",
    "s3fs>=2025.9.0",
    "setuptools>=80.9.0",
    "wheel>=0.45.1",
]
